- name: manager install
  vars:
    manager_path: /usr/share/manager
    manager_data: /var/lib/manager
    manager_port: 8080
  hosts: app
  tasks:
  - name: enable epel
    yum:
      name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: Install easy_install
    yum:
      name:
        - python-setuptools
        - python-pip
        - mono-core.x86_64
      enablerepo: "epel"

  - name: pip dependencies
    # ansible uri module requires httplib2
    pip:
      name:
        - httplib2
        - boto3
        - botocore
      extra_args: "--user"

  - name: set version
    uri:
      url: https://www.manager.io/version.txt
      return_content: yes
    register: this
    #failed_when: "'AWESOME' not in this.content"

  - name: debug version
    debug:
      msg: "Avaliable Manager version is {{ this.content }}"

  - name: create manager folders
    file:
      path: "{{ item }}"
      state: directory
    with_list:
      - "{{ manager_path }}"
      - "{{ manager_data }}"


  - name: extract manager
    unarchive:
      # src: "https://d2ap5zrlkavzl7.cloudfront.net/{{ this.content }}/ManagerServer.tar.gz"
      src: "https://github.com/Manager-io/Manager.zip/releases/latest/download/Manager.zip"
      dest: "{{manager_path}}"
      remote_src: yes

  - firewalld:
      zone: public
      port: "{{ manager_port }}/tcp"
      permanent: yes
      state: enabled     # mono-complete

  - name: create manager service
    template:
      src: manager-server.service.j2
      dest: /etc/systemd/system/manager-server.service

  - name: start manager service
    systemd:
      daemon-reload: yes
      service: manager-server
      state: restarted

  - name: check manager running
    wait_for:
      host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      port: "{{ manager_port }}"
      state: started

